MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Shared/Word/WordManager.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.TestConsole/Program.cs
=> Fix the TableVerticalAlignementValues property for the TableCells

MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Shared/Word/ReportEngine/LabelExtension.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Shared/Word/ReportEngine/StyleExtensions.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.TestConsole/Program.cs
=> Fix accentuates characters for report enginre

MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Shared/Word/ReportEngine/LabelExtension.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.TestConsole/Program.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK/Word/ReportEngine/Models/Label.cs
#25 Add the SpaceProcessingModeValues property to label to preserve empty space in label
=> Fix label empty

MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Shared/Word/ReportEngine/RowExtensions.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.TestConsole/Program.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK/Word/ReportEngine/Models/Row.cs
=> Implement row heigth for report engine

MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Shared/Word/ReportEngine/CellExtensions.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Shared/Word/ReportEngine/ParagraphExtensions.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.TestConsole/Program.cs
#29 Remove the line break when a paragraph is added in a cell
=> Remove empty line break after last paragraph in a cell

MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Shared/Word/ReportEngine/CellExtensions.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.TestConsole/Program.cs
Fix a bug with the new paragraph gestion in a cell : adding a table in a cell make the docx not generated
=> Fix table in cell

MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Shared/Word/ReportEngine/BaseElementExtensions.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Shared/Word/ReportEngine/DocumentExtensions.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Shared/Word/ReportEngine/TableOfContentsExtensions.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.TestConsole/Program.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK/Word/ReportEngine/Models/Document.cs
Make the table of contents positions customisable (in any page instead of the first page)
=> Update table of contents gestion

.gitignore, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Droid/MvvX.Plugins.Open-XML-SDK.Droid.csproj, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.TestConsole/Program.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK/Word/ReportEngine/BatchModels/ContextModel.cs
=> Adding ContextReplacement on Fontcolor property for Labels

MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.TestConsole/Program.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK/Word/ReportEngine/BatchModels/ContextModel.cs
Set paragraphId and Fontcolor for Paragraph from context
Issue #45
=> ReportEngine - Set paragraphId and Fontcolor for Paragraph from context

MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Droid/MvvX.Plugins.Open-XML-SDK.Droid.csproj, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Droid/packages.config, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.TestConsole/MvvX.Plugins.Open-XML-SDK.TestConsole.csproj, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.TestConsole/packages.config, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Touch/MvvX.Plugins.Open-XML-SDK.Touch.csproj, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Touch/packages.config, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Wpf/MvvX.Plugins.Open-XML-SDK.Wpf.csproj, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Wpf/packages.config, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.csproj, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK/packages.config, nuspec/MvvX.Plugins.Open-XML-SDK.nuspec
Upgrade to MvvmCross 5.0.5
Upgrade OpenXML SDK to 2.7.2
Update nuspec file
=> Upgrade packages

MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Shared/Word/ReportEngine/BaseElementExtensions.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Shared/Word/ReportEngine/LabelExtension.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK/Word/ReportEngine/Models/Label.cs
Add html as chunk to the document 
Fix html insertion crash
=> Manage Html in Report engine

MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Shared/Word/ReportEngine/BaseElementExtensions.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK/Word/ReportEngine/Models/Label.cs
(OpenXmlPart insteed of MainPart)
=> Report engine: Manage generic part for label content 

MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Shared/Word/ReportEngine/RowExtensions.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.TestConsole/Program.cs
=> Fix ShowKey for Row

MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Shared/Word/ReportEngine/BaseElementExtensions.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Shared/Word/ReportEngine/ForEachExtensions.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.TestConsole/Program.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK/Word/ReportEngine/BatchModels/ContextModel.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK/Word/ReportEngine/Models/Cell.cs
Adding support of setting Fusion and FusionChild properties from the context in the report engine
=> Adding support of Fusion and FusionChild from context

MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Shared/Word/ReportEngine/CellExtensions.cs
The Render of Cell object still add children when cell.Show == false !!
=> Fix Cell Render

MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Droid/MvvX.Plugins.Open-XML-SDK.Droid.csproj, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Droid/MvvX.Plugins.Open-XML-SDK.Droid.csproj.bak, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Shared/Word/ReportEngine/BarChartExtensions.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK/Word/ReportEngine/Models/Charts/BarModel.cs
=> Add missing functionnalities

MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.TestConsole/Program.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK/Word/ReportEngine/BatchModels/ContextModel.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK/Word/ReportEngine/Models/BaseElement.cs
=> Add BoldKey to allow to bind boldness via the context

MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK/Word/ReportEngine/BatchModels/ContextModel.cs
=> Fix Image convert from base64 in case of context key present but value null

MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Droid/MvvX.Plugins.Open-XML-SDK.Droid.csproj, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Droid/MvvX.Plugins.Open-XML-SDK.Droid.csproj.bak, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Shared/Word/ReportEngine/BarChartExtensions.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.TestConsole/Program.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK/Word/ReportEngine/BatchModels/Charts/BarSerieModel.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK/Word/ReportEngine/Models/Charts/BarSerie.cs
=> Adding support of nullable values

MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Shared/Word/ReportEngine/ImageExtensions.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.TestConsole/Program.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK/Word/ReportEngine/Models/Image.cs
=> Fix image width or height

MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Droid/MvvX.Plugins.Open-XML-SDK.Droid.csproj, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Shared/MvvX.Plugins.Open-XML-SDK.Shared.projitems, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Shared/Word/ReportEngine/DocumentExtensions.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Shared/Word/ReportEngine/ForEachPageExtensions.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.TestConsole/Program.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Touch/MvvX.Plugins.Open-XML-SDK.Touch.csproj, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Wpf/MvvX.Plugins.Open-XML-SDK.Wpf.csproj, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.csproj, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK/Word/ReportEngine/Models/Document.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK/Word/ReportEngine/Models/ForEachPage.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK/Word/ReportEngine/Models/Page.cs
=> Adding support of ForEachPage items in report engine

MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Droid/MvvX.Plugins.Open-XML-SDK.Droid.csproj, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Shared/MvvX.Plugins.Open-XML-SDK.Shared.projitems, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Shared/Word/AutoMapperInitializer.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Shared/Word/Paragraphs/PlatformParagraph.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Shared/Word/Paragraphs/PlatformParagraphBorders.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Shared/Word/Paragraphs/PlatformParagraphProperties.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Shared/Word/PlatformBorder.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Shared/Word/ReportEngine/BorderExtensions.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Shared/Word/WordManager.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.TestConsole/Program.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Touch/MvvX.Plugins.Open-XML-SDK.Touch.csproj, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Wpf/MvvX.Plugins.Open-XML-SDK.Wpf.csproj, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.csproj, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK/Word/IWordManager.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK/Word/Paragraphs/IParagraphBorders.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK/Word/Paragraphs/IParagraphProperties.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK/Word/Paragraphs/Models/ParagraphBorderModel.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK/Word/Paragraphs/Models/ParagraphBordersModel.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK/Word/Paragraphs/Models/ParagraphPropertiesModel.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK/Word/Paragraphs/Models/ParagraphStyleIdModel.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK/Word/ReportEngine/Models/Attributes/BorderModel.cs
=> Paragraph borders color

MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Shared/Word/ReportEngine/DocumentExtensions.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Shared/Word/WordManager.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK/Word/IWordManager.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK/Word/ReportEngine/Report.cs
=> Implement multi reports generation

MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Shared/Word/ReportEngine/LabelExtension.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.TestConsole/Program.cs
=> Fix line break inside labels

MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Shared/Word/ReportEngine/ForEachExtensions.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Shared/Word/ReportEngine/ForEachPageExtensions.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Shared/Word/ReportEngine/TableExtensions.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.TestConsole/Program.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK/Word/ReportEngine/Models/ForEach.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK/Word/ReportEngine/Models/ForEachPage.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK/Word/ReportEngine/Models/Table.cs
Works for ForEach, ForEachPage or Table items.
Issue #99
Wiki description : https://github.com/mathieumack/MvvX.Plugins.Open-XML-SDK/wiki/Report-Engine---Automatic-datasource-context-keys
=> Context add items auto

MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Droid/MvvX.Plugins.Open-XML-SDK.Droid.csproj, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Droid/MvvX.Plugins.Open-XML-SDK.Droid.csproj.bak, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Shared/Word/ReportEngine/BarChartExtensions.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Shared/Word/ReportEngine/BaseElementExtensions.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Shared/Word/ReportEngine/CellExtensions.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Shared/Word/ReportEngine/DocumentExtensions.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Shared/Word/ReportEngine/FooterExtensions.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Shared/Word/ReportEngine/ForEachExtensions.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Shared/Word/ReportEngine/ForEachPageExtensions.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Shared/Word/ReportEngine/HeaderExtensions.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Shared/Word/ReportEngine/LabelExtension.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Shared/Word/ReportEngine/PageExtensions.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Shared/Word/ReportEngine/ParagraphExtensions.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Shared/Word/ReportEngine/RowExtensions.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Shared/Word/ReportEngine/TableExtensions.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Shared/Word/ReportEngine/UniformGridExtensions.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Shared/Word/WordManager.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.TestConsole/Program.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.csproj, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK/Word/IWordManager.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK/Word/ReportEngine/BatchModels/ContextModel.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK/Word/ReportEngine/BatchModels/DateTimeModel.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK/Word/ReportEngine/BatchModels/DoubleModel.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK/Word/ReportEngine/BatchModels/StringModel.cs
Manage DoubleModel et DateTimeModel for the report engine.
Issue #108
=> Double and DateTimes in the report engine (with culture parameter)

MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Shared/Word/ReportEngine/LabelExtension.cs
=> Allow to send empty strings in the context to separate strings

MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Shared/Word/ReportEngine/LabelExtension.cs
=> 110 manage null label

MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Shared/Word/ReportEngine/TableOfContentsExtensions.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.TestConsole/MvvX.Plugins.Open-XML-SDK.TestConsole.csproj, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.TestConsole/Program.cs
=> 113 fix table of content

MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Droid/MvvX.Plugins.Open-XML-SDK.Droid.csproj, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Shared/MvvX.Plugins.Open-XML-SDK.Shared.projitems, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Shared/Word/ReportEngine/BaseElementExtensions.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Shared/Word/ReportEngine/BookmarksExtensions.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Shared/Word/ReportEngine/HyperlinkExtensions.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.TestConsole/Program.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Touch/MvvX.Plugins.Open-XML-SDK.Touch.csproj, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Wpf/MvvX.Plugins.Open-XML-SDK.Wpf.csproj, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.csproj, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK/Word/ReportEngine/BatchModels/ContextModel.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK/Word/ReportEngine/Models/BookmarkEnd.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK/Word/ReportEngine/Models/BookmarkStart.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK/Word/ReportEngine/Models/Hyperlink.cs
And add BookmarkStart/end also ;)
=> Implement the Hyperlink object for the Report Engine

MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Shared/Word/ReportEngine/LabelExtension.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.TestConsole/Program.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.csproj, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK/Word/ReportEngine/Models/Attributes/UnderlineModel.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK/Word/ReportEngine/Models/Attributes/UnderlineValues.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK/Word/ReportEngine/Models/Label.cs
=> Add underline management for labels

MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Droid/MvvX.Plugins.Open-XML-SDK.Droid.csproj, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Shared/Word/ReportEngine/ParagraphExtensions.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.TestConsole/Program.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.TestConsole/Resources/Test.json, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK/Word/ReportEngine/Models/Paragraph.cs
Add ParagraphProperties.KeepLines/KeepNext when Keeplines and KeepNext are true in ParagraphExtensions
=> Add bool KeepLines and bool KeepNext in Paragraph Model

MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Shared/Word/ReportEngine/RowExtensions.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.TestConsole/Program.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.TestConsole/Resources/Test.json, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK/Word/ReportEngine/Models/Row.cs
Add TableRowProperties.CantSplit when CantSplit are true in RowExtensions
Add test CantSplit in Program and Test.Json
=> Add bool CantSplit in Row Model

MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Shared/Word/ReportEngine/ImageExtensions.cs
=> Fix images DPI based on Windows zoom level

MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.TestConsole/Program.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK/Word/ReportEngine/BatchModels/ContextModel.cs
=> Replace all borders colors in context, not only the main color

MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.Shared/Word/ReportEngine/UniformGridExtensions.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK.TestConsole/Program.cs, MvvX.Plugins.Open-XML-SDK/MvvX.Plugins.Open-XML-SDK/Word/ReportEngine/Models/UniformGrid.cs
=> Add the "Can't split" property on the UniformGrid for all rows

OpenXMLSDK.Engine/interfaces/Word/ReportEngine/Models/Label.cs, OpenXMLSDK.Engine/interfaces/Word/ReportEngine/Models/LabelTransformOperation.cs, OpenXMLSDK.Engine/interfaces/Word/ReportEngine/Models/LabelTransformOperationType.cs, OpenXMLSDK.Engine/interfaces/Word/ReportEngine/Renders/LabelExtension.cs, OpenXMLSDK.UnitTest/ReportEngine/ReportEngineTest.cs
Now, on labels, you can add operations like :
- ToUpper
- ToLower
- ToUpperInvariant
- ToLowerInvariant
- Trim
- TrimStart
- TrimEnd
=> Add labels transform operations

OpenXMLSDK.Engine/interfaces/Word/ReportEngine/Renders/ForEachExtensions.cs, OpenXMLSDK.Engine/interfaces/Word/ReportEngine/Renders/ForEachPageExtensions.cs, OpenXMLSDK.Engine/interfaces/Word/ReportEngine/Renders/TableExtensions.cs
Add automatic keys for :
- Foreach
- ForeachPage
- Table
Issue #143
=> Add automatic Even and Odd keys on renders

OpenXMLSDK.Engine/interfaces/Word/ReportEngine/BatchModels/ContextModel.cs, OpenXMLSDK.Engine/interfaces/Word/ReportEngine/Models/Paragraph.cs, OpenXMLSDK.Engine/interfaces/Word/ReportEngine/Renders/ParagraphExtensions.cs
Paragraphs :
Add page break before Paragraphs with the Property "PageBreakBefore"
A PageBreakBeforeShowKey property allow you to change the value by a ContextModel value
=> Report engine : Add Page Break

OpenXMLSDK.Engine/interfaces/Word/ReportEngine/Models/BaseElement.cs, OpenXMLSDK.Engine/interfaces/Word/ReportEngine/Models/Document.cs, OpenXMLSDK.Engine/interfaces/Word/ReportEngine/Models/TemplateDefinition.cs, OpenXMLSDK.Engine/interfaces/Word/ReportEngine/Models/TemplateModel.cs, OpenXMLSDK.Engine/interfaces/Word/ReportEngine/Renders/BaseElementExtensions.cs, OpenXMLSDK.Engine/interfaces/Word/ReportEngine/Renders/CellExtensions.cs, OpenXMLSDK.Engine/interfaces/Word/ReportEngine/Renders/DocumentExtensions.cs, OpenXMLSDK.Engine/interfaces/Word/ReportEngine/Renders/FooterExtensions.cs, OpenXMLSDK.Engine/interfaces/Word/ReportEngine/Renders/ForEachExtensions.cs, OpenXMLSDK.Engine/interfaces/Word/ReportEngine/Renders/ForEachPageExtensions.cs, OpenXMLSDK.Engine/interfaces/Word/ReportEngine/Renders/HeaderExtensions.cs, OpenXMLSDK.Engine/interfaces/Word/ReportEngine/Renders/PageExtensions.cs, OpenXMLSDK.Engine/interfaces/Word/ReportEngine/Renders/RowExtensions.cs, OpenXMLSDK.Engine/interfaces/Word/ReportEngine/Renders/TableExtensions.cs, OpenXMLSDK.Engine/interfaces/Word/ReportEngine/Renders/TemplateModelExtensions.cs, OpenXMLSDK.Engine/interfaces/Word/ReportEngine/Renders/UniformGridExtensions.cs, OpenXMLSDK.Engine/interfaces/Word/WordManager.cs, OpenXMLSDK.UnitTest/ReportEngine/ReportEngineTest.cs
On document objet you can add some templates.
On Template, you can create TemplateModel objects that reference a Template definition by an Identifier
=> Add template definitions

OpenXMLSDK.Engine/interfaces/Word/ReportEngine/Renders/ForEachExtensions.cs, OpenXMLSDK.Engine/interfaces/Word/ReportEngine/Renders/ForEachPageExtensions.cs, OpenXMLSDK.Engine/interfaces/Word/ReportEngine/Renders/TableExtensions.cs
=> Add new automatic keys

OpenXMLSDK.Engine/interfaces/Word/ReportEngine/BatchModels/ContextModel.cs, OpenXMLSDK.Engine/interfaces/Word/ReportEngine/Models/HtmlContent.cs, OpenXMLSDK.Engine/interfaces/Word/ReportEngine/Models/Label.cs, OpenXMLSDK.Engine/interfaces/Word/ReportEngine/Renders/BaseElementExtensions.cs, OpenXMLSDK.Engine/interfaces/Word/ReportEngine/Renders/CellExtensions.cs, OpenXMLSDK.Engine/interfaces/Word/ReportEngine/Renders/HtmlContentExtensions.cs, OpenXMLSDK.Engine/interfaces/Word/ReportEngine/Renders/LabelExtension.cs
The label object doesn't contains anymore the IsHTML field.
A new HtmlContent object is created.
=> Add a new HtmlContent object 

OpenXMLSDK.Engine/Word/ReportEngine/Renders/ImageExtensions.cs
=> Take resolution unit into account to calculate image size

OpenXMLSDK.Engine/Word/ReportEngine/Models/Charts/DataLabelModel.cs, OpenXMLSDK.Engine/Word/ReportEngine/Renders/BarChartExtensions.cs, OpenXMLSDK.Engine/Word/ReportEngine/Renders/PieChartExtensions.cs, OpenXMLSDK.UnitTest/ReportEngine/ReportEngineTest.cs
Allow set font size of label of Charts (Pie and Bar)
=> Allow set font size of label of Charts (Pie and Bar)

OpenXMLSDK.Engine/Word/Extensions/BarChartScalingModelExtensions.cs, OpenXMLSDK.Engine/Word/ReportEngine/Models/Charts/BarChartOrientationType.cs, OpenXMLSDK.Engine/Word/ReportEngine/Models/Charts/BarChartScalingModel.cs, OpenXMLSDK.Engine/Word/ReportEngine/Models/Charts/BarModel.cs, OpenXMLSDK.Engine/Word/ReportEngine/Renders/BarChartExtensions.cs, OpenXMLSDK.UnitTest/ReportEngine/ReportEngineTest.cs
=> Add scaling ability to the BarModel's values axis

OpenXMLSDK.Engine/Word/ReportEngine/Models/Cell.cs, OpenXMLSDK.Engine/Word/ReportEngine/Renders/CellExtensions.cs, OpenXMLSDK.UnitTest/ReportEngine/ReportEngineTest.cs
- Add NoWrap property in cell
- Update Cell render with NoWrap
- Add test
=> Add no wrap property in cell

OpenXMLSDK.Engine/ReportEngine/DataContext/ContextModel.cs, OpenXMLSDK.Engine/Word/ReportEngine/Models/Cell.cs, OpenXMLSDK.UnitTest/ReportEngine/ReportEngineTest.cs
- Add ColSpanKey property in Cell Model
- Update ContextModel ReplaceItem method
- Add test
=> Add Colspan key property in Cell

OpenXMLSDK.Engine/ReportEngine/DataContext/ContextModel.cs, OpenXMLSDK.Engine/Word/ReportEngine/Renders/BarChartExtensions.cs, OpenXMLSDK.Engine/Word/ReportEngine/Renders/ForEachExtensions.cs, OpenXMLSDK.Engine/Word/ReportEngine/Renders/ForEachPageExtensions.cs, OpenXMLSDK.Engine/Word/ReportEngine/Renders/PageExtensions.cs, OpenXMLSDK.Engine/Word/ReportEngine/Renders/PieChartExtensions.cs, OpenXMLSDK.Engine/Word/ReportEngine/Renders/RowExtensions.cs, OpenXMLSDK.Engine/Word/ReportEngine/Renders/TableExtensions.cs, OpenXMLSDK.Engine/Word/ReportEngine/Renders/UniformGridExtensions.cs
Improve ContextModel dictionary item management
Avoid checking several times a null or empty key, perform get item only once and improve casting
=> Add TryGetItem method to ContextModel

OpenXMLSDK.Engine/Word/ReportEngine/Renders/CellExtensions.cs
Use return null instead of TableCell
=> Fix cell show property

OpenXMLSDK.Engine/ReportEngine/DataContext/ContextModel.cs, OpenXMLSDK.Engine/Word/ReportEngine/Models/SimpleField.cs, OpenXMLSDK.Engine/Word/ReportEngine/Renders/BaseElementExtensions.cs, OpenXMLSDK.Engine/Word/ReportEngine/Renders/SimpleFieldExtensions.cs, OpenXMLSDK.UnitTest/ReportEngine/ReportEngineTest.cs
- Create SimpleField Model
- Create Extensions
- Add test
=> Add SimpleField for page reference to bookmark and create table of content simply

OpenXMLSDK.Engine/Word/ReportEngine/Renders/ForEachExtensions.cs, OpenXMLSDK.Engine/Word/ReportEngine/Renders/TemplateModelExtensions.cs, OpenXMLSDK.UnitTest/ReportEngine/ReportEngineTest.cs, OpenXMLSDK.UnitTest/ReportEngine/ReportEngineUnitTests.cs
Read template ID from context and update it
=> Read template ID from context and update it

OpenXMLSDK.Engine/Word/ReportEngine/Renders/CellExtensions.cs
=> Fix alternate cell configuration values when there are null values

OpenXMLSDK.Engine/OpenXMLSDK.Engine.csproj, OpenXMLSDK.UnitTest/OpenXMLSDK.UnitTest.csproj
* Update to OpenXML 2.11.1
* Update Unit test framework packages
Resolves #206
=> Update all packages

OpenXMLSDK.Engine/OpenXMLSDK.Engine.csproj, OpenXMLSDK.Engine/ReportEngine/DataContext/Charts/AxisModel.cs, OpenXMLSDK.Engine/ReportEngine/DataContext/Charts/MultipleSeriesModel.cs, OpenXMLSDK.Engine/ReportEngine/DataContext/Charts/PresetLineDashValues.cs, OpenXMLSDK.Engine/ReportEngine/DataContext/Charts/SerieChartType.cs, OpenXMLSDK.Engine/ReportEngine/DataContext/Charts/SerieModel.cs, OpenXMLSDK.Engine/ReportEngine/DataContext/Charts/SingleSeriesModel.cs, OpenXMLSDK.Engine/ReportEngine/DataContext/ContextModel.cs, OpenXMLSDK.Engine/Word/Extensions/BarChartScalingModelExtensions.cs, OpenXMLSDK.Engine/Word/Extensions/ScalingModelExtensions.cs, OpenXMLSDK.Engine/Word/ReportEngine/Models/Charts/ChartAxisModel.cs, OpenXMLSDK.Engine/Word/ReportEngine/Models/Charts/ChartModel.cs, OpenXMLSDK.Engine/Word/ReportEngine/Models/Charts/ChartSerie.cs, OpenXMLSDK.Engine/Word/ReportEngine/Models/Charts/CombineChartModel.cs, OpenXMLSDK.Engine/Word/ReportEngine/Models/Charts/GroupingValues.cs, OpenXMLSDK.Engine/Word/ReportEngine/Models/Charts/LegendPositionValues.cs, OpenXMLSDK.Engine/Word/ReportEngine/Models/Charts/LineCategory.cs, OpenXMLSDK.Engine/Word/ReportEngine/Models/Charts/LineModel.cs, OpenXMLSDK.Engine/Word/ReportEngine/Models/Charts/LineSerie.cs, OpenXMLSDK.Engine/Word/ReportEngine/Models/Charts/LineSerieMarker.cs, OpenXMLSDK.Engine/Word/ReportEngine/Models/Charts/MarkerStyleValues.cs, OpenXMLSDK.Engine/Word/ReportEngine/Models/Charts/OrientationType.cs, OpenXMLSDK.Engine/Word/ReportEngine/Models/Charts/ScalingModel.cs, OpenXMLSDK.Engine/Word/ReportEngine/Renders/BarChartExtensions.cs, OpenXMLSDK.Engine/Word/ReportEngine/Renders/BaseElementExtensions.cs, OpenXMLSDK.Engine/Word/ReportEngine/Renders/CombineChartExtensions.cs, OpenXMLSDK.Engine/Word/ReportEngine/Renders/ImageExtensions.cs, OpenXMLSDK.Engine/Word/ReportEngine/Renders/LineChartExtensions.cs, OpenXMLSDK.Engine/Word/ReportEngine/Renders/PieChartExtensions.cs, OpenXMLSDK.UnitTest/ReportEngine/ReportEngineTest.cs
Implement Line chart with customization
close #211
=> Implement Line chart

OpenXMLSDK.Engine/ReportEngine/DataContext/Charts/AxisModel.cs, OpenXMLSDK.Engine/ReportEngine/DataContext/ContextModel.cs, OpenXMLSDK.Engine/Word/ReportEngine/Models/Charts/ChartAxisModel.cs, OpenXMLSDK.Engine/Word/ReportEngine/Renders/BarChartExtensions.cs, OpenXMLSDK.Engine/Word/ReportEngine/Renders/CombineChartExtensions.cs, OpenXMLSDK.Engine/Word/ReportEngine/Renders/LineChartExtensions.cs, OpenXMLSDK.UnitTest/ReportEngine/ReportEngineTest.cs
Allow to select the crosses value for graphs
Add label format for axes titles
close #213
=> Allow to select the crosses value for graphs and add axes' label format

OpenXMLSDK.Engine/ReportEngine/DataContext/Charts/CategoryModel.cs, OpenXMLSDK.Engine/ReportEngine/DataContext/Charts/CategoryType.cs, OpenXMLSDK.Engine/ReportEngine/DataContext/Charts/CategoryTypes.cs, OpenXMLSDK.Engine/ReportEngine/DataContext/Charts/MultipleSeriesModel.cs, OpenXMLSDK.Engine/Word/ReportEngine/Models/Charts/ChartCategory.cs, OpenXMLSDK.Engine/Word/ReportEngine/Models/Charts/ChartModel.cs, OpenXMLSDK.Engine/Word/ReportEngine/Renders/BarChartExtensions.cs, OpenXMLSDK.Engine/Word/ReportEngine/Renders/CombineChartExtensions.cs, OpenXMLSDK.Engine/Word/ReportEngine/Renders/LineChartExtensions.cs, OpenXMLSDK.UnitTest/ReportEngine/ReportEngineTest.cs
=> Manage numeric categories

OpenXMLSDK.Engine/Word/ColumnCountValues.cs, OpenXMLSDK.Engine/Word/MarkSectionValues.cs, OpenXMLSDK.Engine/Word/ReportEngine/Models/Column.cs, OpenXMLSDK.Engine/Word/ReportEngine/Models/Page.cs, OpenXMLSDK.Engine/Word/ReportEngine/Models/Paragraph.cs, OpenXMLSDK.Engine/Word/ReportEngine/Renders/PageExtensions.cs, OpenXMLSDK.Engine/Word/ReportEngine/Renders/ParagraphExtensions.cs, OpenXMLSDK.UnitTest/ReportEngine/ReportEngineTest.cs
Add Column property on page to allow split content in 1, 2 or 3 columns.
=> Add ColumnCount property on page to split content

OpenXMLSDK.UnitTest/ReportEngine/ReportEngineTest.cs
=> Clean test method for a better understanding

src/OpenXMLSDK.Engine/Word/ReportEngine/Models/Hyperlink.cs, src/OpenXMLSDK.Engine/Word/ReportEngine/Renders/HyperlinkExtensions.cs, src/OpenXMLSDK.Engine/Word/ReportEngine/Renders/ImageExtensions.cs, src/OpenXMLSDK.UnitTest/ReportEngine/ReportEngineTest.cs
Import the code from the #235 because of build validation.
The code was created by Sylvain Turpault
=> Allow to add an hyperlink on an image #234

.github/workflows/ci.yml, README.md, src/OpenXMLSDK.Engine/OpenXMLSDK.Engine.csproj, src/OpenXMLSDK.Engine/Word/ReportEngine/Renders/ImageExtensions.cs, src/OpenXMLSDK.UnitTest/OpenXMLSDK.UnitTest.csproj
Also change Imagesharp to "LazZiya.ImageResize.
Update ci to manage .net 6 and 7.
Linked to #241
=> Upgrade solution to support natively .net 6 and 7.

src/OpenXMLSDK.Engine/Word/Bookmarks/BookmarkExtensions.cs, src/OpenXMLSDK.Engine/Word/Parts/PartsExtensions.cs, src/OpenXMLSDK.Engine/Word/ReportEngine/GenerateReportExtensions.cs, src/OpenXMLSDK.Engine/Word/WordManager.cs, src/OpenXMLSDK.UnitTest/Managers/Word/WordManagerNewTests.cs
Movesome function in extensions and review documentation
=> Add New() function to create a new empty document
